package lab

import (
	"context"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	dynamicfake "k8s.io/client-go/dynamic/fake"
	k8stesting "k8s.io/client-go/testing"

	"github.com/course-go-autumn-2026/tripgo-infra/internal/catalog"
	"github.com/course-go-autumn-2026/tripgo-infra/internal/cluster"
	configenv "github.com/course-go-autumn-2026/tripgo-infra/internal/environment"
	"github.com/course-go-autumn-2026/tripgo-infra/internal/generator"
	redpandaconfig "github.com/course-go-autumn-2026/tripgo-infra/internal/redpanda"
)

func TestWriteEnvIncludesStableLiteralCustomVariables(t *testing.T) {
	t.Parallel()
	directory := t.TempDir()
	config, err := configenv.Parse("environment.toml", []byte("schema_version = 1\nlab = 1\ncomponents = [\"postgres\"]\n[env]\nZ_LAST = \"${UNCHANGED}\"\nA_FIRST = \"value with spaces\"\nCOMMAND_SUBSTITUTION = \"$(touch /tmp/tripgo-must-not-run)\"\n"))
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(directory, ".env")
	if err := writeEnv(path, config, "v1.0.0"); err != nil {
		t.Fatal(err)
	}
	content, err := os.ReadFile(path) // #nosec G304 -- test path is beneath t.TempDir.
	if err != nil {
		t.Fatal(err)
	}
	text := string(content)
	for _, expected := range []string{
		envMarker + "\n",
		"# Source: environment.toml\n# Lab: 1\n# Generator: tripgoctl v1.0.0\n",
		"DATABASE_URL=postgres://tripgo:tripgo@localhost:21032/tripgo?sslmode=disable\n",
		"A_FIRST=value with spaces\nCOMMAND_SUBSTITUTION=$(touch /tmp/tripgo-must-not-run)\nZ_LAST=${UNCHANGED}\n",
	} {
		if !strings.Contains(text, expected) {
			t.Errorf("generated .env does not contain %q:\n%s", expected, text)
		}
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if got := info.Mode().Perm(); got != 0o600 {
		t.Fatalf(".env mode = %o", got)
	}
}

func TestWriteEnvAtomicallyReplacesGeneratedFileWithoutStagingResidue(t *testing.T) {
	t.Parallel()
	directory := t.TempDir()
	path := filepath.Join(directory, ".env")
	if err := os.WriteFile(path, []byte(envMarker+"\nOLD=value\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	config, err := configenv.Parse("environment.toml", []byte("schema_version = 1\nlab = 1\ncomponents = [\"postgres\"]\n"))
	if err != nil {
		t.Fatal(err)
	}
	if err := writeEnv(path, config, "v1.0.0"); err != nil {
		t.Fatal(err)
	}
	content, err := os.ReadFile(path) // #nosec G304 -- test path is beneath t.TempDir.
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(content), "OLD=value") || !strings.Contains(string(content), "# Generator: tripgoctl v1.0.0") {
		t.Fatalf("replacement .env = %q", content)
	}
	entries, err := os.ReadDir(directory)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 1 || entries[0].Name() != ".env" {
		t.Fatalf("atomic replacement left files: %v", entries)
	}
}

func TestWriteEnvRefusesUserFile(t *testing.T) {
	t.Parallel()
	path := filepath.Join(t.TempDir(), ".env")
	if err := os.WriteFile(path, []byte("USER_VALUE=keep\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	config, err := configenv.Parse("environment.toml", []byte("schema_version = 1\nlab = 1\ncomponents = [\"postgres\"]\n"))
	if err != nil {
		t.Fatal(err)
	}
	err = writeEnv(path, config, "dev")
	if !errors.Is(err, cluster.ErrConflict) {
		t.Fatalf("writeEnv error = %v", err)
	}
	content, _ := os.ReadFile(path) // #nosec G304 -- test path is beneath t.TempDir.
	if got := string(content); got != "USER_VALUE=keep\n" {
		t.Fatalf("user .env changed to %q", got)
	}
}

func TestRecoverInterruptedLocalStateRestoresOnlyOwnedBackup(t *testing.T) {
	t.Parallel()
	cwd := t.TempDir()
	owned := filepath.Join(cwd, ".tripgo-previous-owned")
	unowned := filepath.Join(cwd, ".tripgo-render-unowned")
	if err := os.MkdirAll(owned, 0o700); err != nil {
		t.Fatal(err)
	}
	lock := "# Generated by tripgoctl. Do not edit manually.\nlab = 1\nnamespace = \"tripgo-lab-01\"\ncluster_id = \"cluster-id\"\n"
	if err := os.WriteFile(filepath.Join(owned, "environment.lock"), []byte(lock), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(unowned, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := recoverInterruptedLocalState(cwd, 1, "tripgo-lab-01", "cluster-id"); err != nil {
		t.Fatal(err)
	}
	if err := verifyLockFile(filepath.Join(cwd, ".tripgo", "environment.lock"), 1, "tripgo-lab-01", "cluster-id"); err != nil {
		t.Fatalf("owned backup was not restored: %v", err)
	}
	if _, err := os.Stat(unowned); err != nil {
		t.Fatalf("unverifiable stale directory was not preserved: %v", err)
	}
}

func TestEnsureTripgoWritableRejectsUserDirectory(t *testing.T) {
	t.Parallel()
	path := filepath.Join(t.TempDir(), ".tripgo")
	if err := os.Mkdir(path, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(path, "notes"), []byte("keep"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := ensureTripgoWritable(path, 1, "tripgo-lab-01", "cluster-id"); !errors.Is(err, cluster.ErrConflict) {
		t.Fatalf("ensureTripgoWritable error = %v", err)
	}
}

func TestEnsureTripgoWritablePreservesLockReadError(t *testing.T) {
	t.Parallel()
	path := filepath.Join(t.TempDir(), ".tripgo")
	if err := os.MkdirAll(path, 0o700); err != nil {
		t.Fatal(err)
	}
	lockPath := filepath.Join(path, "environment.lock")
	if err := os.WriteFile(lockPath, []byte("unreadable"), 0o000); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(lockPath, 0o600) })
	err := ensureTripgoWritable(path, 1, "tripgo-lab-01", "cluster-id")
	if err == nil || errors.Is(err, cluster.ErrConflict) || !strings.Contains(err.Error(), "read environment.lock") {
		t.Fatalf("ensureTripgoWritable error = %v", err)
	}
}

func TestRemoveGeneratedPreservesUserFiles(t *testing.T) {
	t.Parallel()
	directory := t.TempDir()
	envPath := filepath.Join(directory, ".env")
	if err := os.WriteFile(envPath, []byte("USER_VALUE=keep\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	tripgoPath := filepath.Join(directory, ".tripgo")
	if err := os.Mkdir(tripgoPath, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(tripgoPath, "environment.lock"), []byte("user data\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := removeGenerated(envPath, false, 1, "tripgo-lab-01", "cluster-id"); err != nil {
		t.Fatal(err)
	}
	if err := removeGenerated(tripgoPath, true, 1, "tripgo-lab-01", "cluster-id"); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(envPath); err != nil {
		t.Fatalf("user .env was removed: %v", err)
	}
	if _, err := os.Stat(tripgoPath); err != nil {
		t.Fatalf("user .tripgo was removed: %v", err)
	}
}

func TestLoadCurrentConfigAcceptsLabsThrough5(t *testing.T) {
	t.Parallel()
	directory := t.TempDir()
	if err := os.WriteFile(filepath.Join(directory, "environment.toml"), []byte("schema_version = 1\nlab = 3\ncomponents = [\"postgres\", \"observability\", \"push\"]\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	config, err := loadCurrentConfig(directory)
	if err != nil || config.Lab != 3 {
		t.Fatalf("loadCurrentConfig lab 3 = %+v, %v", config, err)
	}
	if err := os.WriteFile(filepath.Join(directory, "environment.toml"), []byte("schema_version = 1\nlab = 4\ncomponents = [\"postgres\", \"observability\", \"push\", \"redpanda\"]\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	config, err = loadCurrentConfig(directory)
	if err != nil || config.Lab != 4 {
		t.Fatalf("loadCurrentConfig lab 4 = %+v, %v", config, err)
	}
	if err := os.WriteFile(filepath.Join(directory, "environment.toml"), []byte("schema_version = 1\nlab = 5\ncomponents = [\"postgres\", \"observability\", \"push\", \"redpanda\"]\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	config, err = loadCurrentConfig(directory)
	if err != nil || config.Lab != 5 {
		t.Fatalf("loadCurrentConfig lab 5 = %+v, %v", config, err)
	}
}

func TestStatusWithRequiresExactOwnershipAndReportsReadiness(t *testing.T) {
	t.Parallel()
	namespace := &unstructured.Unstructured{Object: map[string]any{
		"apiVersion": "v1", "kind": "Namespace",
		"metadata": map[string]any{
			"name": "tripgo-lab-01",
			"labels": map[string]any{
				"app.kubernetes.io/managed-by": "tripgoctl",
				"app.kubernetes.io/part-of":    "tripgo-local",
				"tripgo.course/lab":            "01",
				"tripgo.course/environment":    "tripgo-lab-01",
			},
			"annotations": map[string]any{"tripgo.course/cluster-id": "cluster-id"},
		},
	}}
	deployment := &unstructured.Unstructured{Object: map[string]any{
		"apiVersion": "apps/v1", "kind": "Deployment",
		"metadata": map[string]any{
			"name": "postgres", "namespace": "tripgo-lab-01", "generation": int64(2),
			"labels": map[string]any{
				"app.kubernetes.io/managed-by": "tripgoctl", "app.kubernetes.io/part-of": "tripgo-local",
				"tripgo.course/lab": "01", "tripgo.course/environment": "tripgo-lab-01",
			},
			"annotations": map[string]any{"tripgo.course/cluster-id": "cluster-id"},
		},
		"spec": map[string]any{
			"replicas": int64(1),
			"template": map[string]any{"spec": map[string]any{"containers": []any{map[string]any{"image": "docker.io/postgres@sha256:" + strings.Repeat("a", 64)}}}},
		},
		"status": map[string]any{"observedGeneration": int64(2), "updatedReplicas": int64(1), "readyReplicas": int64(1), "availableReplicas": int64(1)},
	}}
	serviceObject := &unstructured.Unstructured{Object: map[string]any{
		"apiVersion": "v1", "kind": "Service",
		"metadata": map[string]any{
			"name": "postgres", "namespace": "tripgo-lab-01",
			"labels": map[string]any{
				"app.kubernetes.io/managed-by": "tripgoctl", "app.kubernetes.io/part-of": "tripgo-local",
				"tripgo.course/lab": "01", "tripgo.course/environment": "tripgo-lab-01",
			},
			"annotations": map[string]any{"tripgo.course/cluster-id": "cluster-id"},
		},
		"spec": map[string]any{
			"type":     "NodePort",
			"selector": map[string]any{"app.kubernetes.io/name": "postgres", "app.kubernetes.io/instance": "tripgo-lab-01-postgres"},
			"ports":    []any{map[string]any{"name": "postgres", "port": int64(5432), "targetPort": "postgres", "nodePort": int64(30103)}},
		},
	}}
	client := dynamicfake.NewSimpleDynamicClient(runtime.NewScheme(), namespace, deployment, serviceObject)
	service := &Service{}
	config := configenv.Config{SchemaVersion: 1, Lab: 1}
	config.Components, _ = catalog.Components(1)
	status, err := service.statusWith(t.Context(), client, config, "cluster-id")
	if err != nil {
		t.Fatal(err)
	}
	if status.State != "ready" || status.Components[0].Ready != 1 || status.Components[0].ImageDigest != "sha256:"+strings.Repeat("a", 64) {
		t.Fatalf("status = %+v", status)
	}
	_, err = service.statusWith(t.Context(), client, config, "another-cluster")
	if !errors.Is(err, cluster.ErrConflict) {
		t.Fatalf("ownership error = %v", err)
	}
	if err := client.Resource(serviceResource).Namespace("tripgo-lab-01").Delete(t.Context(), "postgres", metav1.DeleteOptions{}); err != nil {
		t.Fatal(err)
	}
	_, err = service.statusWith(t.Context(), client, config, "cluster-id")
	if !errors.Is(err, cluster.ErrPrerequisite) {
		t.Fatalf("missing service error = %v", err)
	}
}

func TestWaitForWorkloadsReportsComponentSpecificReadinessOnCancellation(t *testing.T) {
	t.Parallel()
	deployment := &unstructured.Unstructured{Object: map[string]any{
		"apiVersion": "apps/v1", "kind": "Deployment",
		"metadata": map[string]any{"name": "postgres", "namespace": "tripgo-lab-01", "generation": int64(3)},
		"spec":     map[string]any{"replicas": int64(1)},
		"status":   map[string]any{"observedGeneration": int64(2), "readyReplicas": int64(0)},
	}}
	client := dynamicfake.NewSimpleDynamicClient(runtime.NewScheme(), deployment)
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Millisecond)
	defer cancel()
	err := waitForWorkloads(ctx, client, "tripgo-lab-01", []workload{{name: "postgres", resource: deploymentResource}}, 1)
	if err == nil || !strings.Contains(err.Error(), "postgres (desired=1 ready=0 generation=3 observed=2)") {
		t.Fatalf("readiness error = %v", err)
	}
}

func TestResourceForSupportsStatefulSet(t *testing.T) {
	t.Parallel()
	resource, err := resourceFor("apps/v1", "StatefulSet")
	if err != nil {
		t.Fatal(err)
	}
	if resource != statefulSetResource {
		t.Fatalf("StatefulSet resource = %#v", resource)
	}
}

func TestWorkloadsIncludeRedpandaStatefulSetAndReconciler(t *testing.T) {
	t.Parallel()
	items := workloads(4)
	found := map[string]schema.GroupVersionResource{}
	for _, item := range items {
		found[item.name] = item.resource
	}
	if found["redpanda"] != statefulSetResource || found["redpanda-console"] != deploymentResource || found["redpanda-topic-reconciler"] != deploymentResource {
		t.Fatalf("lab 4 workloads = %#v", found)
	}
}

func TestManifestBundleOwnershipPreflightRefusesForeignResource(t *testing.T) {
	t.Parallel()
	foreign := &unstructured.Unstructured{Object: map[string]any{
		"apiVersion": "v1", "kind": "Service",
		"metadata": map[string]any{"name": "redpanda-console", "namespace": "tripgo-lab-04"},
	}}
	client := dynamicfake.NewSimpleDynamicClient(runtime.NewScheme(), foreign)
	bundle := generator.Bundle{Files: []generator.File{{Name: "redpanda.yaml", Content: []byte(`apiVersion: v1
kind: Service
metadata:
  name: redpanda-console
  namespace: tripgo-lab-04
`)}}}
	err := verifyManifestBundleOwnership(t.Context(), client, bundle, 4, "tripgo-lab-04", "cluster-id")
	if !errors.Is(err, cluster.ErrConflict) {
		t.Fatalf("ownership preflight error = %v", err)
	}
}

func TestApplyManifestReconcilesMissingResourceInPartialNamespace(t *testing.T) {
	t.Parallel()
	client := dynamicfake.NewSimpleDynamicClient(runtime.NewScheme())
	client.PrependReactor("patch", "configmaps", func(action k8stesting.Action) (bool, runtime.Object, error) {
		patch := action.(k8stesting.PatchAction)
		object := &unstructured.Unstructured{Object: map[string]any{}}
		if err := json.Unmarshal(patch.GetPatch(), &object.Object); err != nil {
			return true, nil, err
		}
		if err := client.Tracker().Create(configMapResource, object, patch.GetNamespace()); err != nil {
			return true, nil, err
		}
		return true, object, nil
	})
	manifest := []byte(`apiVersion: v1
kind: ConfigMap
metadata:
  name: recovered
  namespace: tripgo-lab-01
  labels:
    app.kubernetes.io/managed-by: tripgoctl
    app.kubernetes.io/part-of: tripgo-local
    tripgo.course/lab: "01"
    tripgo.course/environment: tripgo-lab-01
  annotations:
    tripgo.course/cluster-id: cluster-id
data:
  recovered: "true"
`)
	if err := applyManifest(t.Context(), client, manifest, 1, "tripgo-lab-01", "cluster-id"); err != nil {
		t.Fatal(err)
	}
	object, err := client.Resource(configMapResource).Namespace("tripgo-lab-01").Get(t.Context(), "recovered", metav1.GetOptions{})
	if err != nil || object.GetAnnotations()["tripgo.course/cluster-id"] != "cluster-id" {
		t.Fatalf("reconciled object = %#v, %v", object, err)
	}
}

func TestApplyManifestRefusesForeignNamedResource(t *testing.T) {
	t.Parallel()
	foreign := &unstructured.Unstructured{Object: map[string]any{
		"apiVersion": "v1", "kind": "Secret",
		"metadata":   map[string]any{"name": "postgres", "namespace": "tripgo-lab-01"},
		"stringData": map[string]any{"POSTGRES_PASSWORD": "keep"},
	}}
	client := dynamicfake.NewSimpleDynamicClient(runtime.NewScheme(), foreign)
	manifest := []byte(`apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: tripgo-lab-01
  labels:
    app.kubernetes.io/managed-by: tripgoctl
    app.kubernetes.io/part-of: tripgo-local
    tripgo.course/lab: "01"
    tripgo.course/environment: tripgo-lab-01
  annotations:
    tripgo.course/cluster-id: cluster-id
stringData:
  POSTGRES_PASSWORD: tripgo
`)
	err := applyManifest(t.Context(), client, manifest, 1, "tripgo-lab-01", "cluster-id")
	if !errors.Is(err, cluster.ErrConflict) {
		t.Fatalf("applyManifest error = %v", err)
	}
}

func TestVerifyRedpandaResourcesRejectsOwnedTopicConfigDrift(t *testing.T) {
	t.Parallel()
	data := redpandaconfig.ConfigMapData()
	data["topics"] = strings.Replace(data["topics"], "trip.events.v1=3", "trip.events.v1=4", 1)
	configMap := &unstructured.Unstructured{Object: map[string]any{
		"apiVersion": "v1", "kind": "ConfigMap",
		"metadata": map[string]any{
			"name": "redpanda-topics", "namespace": "tripgo-lab-04",
			"labels": map[string]any{
				"app.kubernetes.io/managed-by": "tripgoctl", "app.kubernetes.io/part-of": "tripgo-local",
				"tripgo.course/lab": "04", "tripgo.course/environment": "tripgo-lab-04",
			},
			"annotations": map[string]any{"tripgo.course/cluster-id": "cluster-id"},
		},
		"data": map[string]any{"topics": data["topics"], "reconcile.sh": data["reconcile.sh"]},
	}}
	client := dynamicfake.NewSimpleDynamicClient(runtime.NewScheme(), configMap)
	err := verifyRedpandaResources(t.Context(), client, 4, "tripgo-lab-04", "cluster-id")
	if !errors.Is(err, cluster.ErrConflict) || !strings.Contains(err.Error(), "reconciliation contract") {
		t.Fatalf("verifyRedpandaResources drift error = %v", err)
	}
}

func TestVerifyRedpandaResourcesRejectsOwnedReconcilerDrift(t *testing.T) {
	t.Parallel()
	data := redpandaconfig.ConfigMapData()
	data["reconcile.sh"] += "echo drift\n"
	configMap := &unstructured.Unstructured{Object: map[string]any{
		"apiVersion": "v1", "kind": "ConfigMap",
		"metadata": map[string]any{
			"name": "redpanda-topics", "namespace": "tripgo-lab-04",
			"labels": map[string]any{
				"app.kubernetes.io/managed-by": "tripgoctl", "app.kubernetes.io/part-of": "tripgo-local",
				"tripgo.course/lab": "04", "tripgo.course/environment": "tripgo-lab-04",
			},
			"annotations": map[string]any{"tripgo.course/cluster-id": "cluster-id"},
		},
		"data": map[string]any{"topics": data["topics"], "reconcile.sh": data["reconcile.sh"]},
	}}
	client := dynamicfake.NewSimpleDynamicClient(runtime.NewScheme(), configMap)
	err := verifyRedpandaResources(t.Context(), client, 4, "tripgo-lab-04", "cluster-id")
	if !errors.Is(err, cluster.ErrConflict) {
		t.Fatalf("verifyRedpandaResources script drift error = %v", err)
	}
}

func TestVerifyJaegerOTLPServiceRejectsDrift(t *testing.T) {
	t.Parallel()
	service := &unstructured.Unstructured{Object: map[string]any{
		"apiVersion": "v1", "kind": "Service",
		"metadata": map[string]any{
			"name": "jaeger-otlp", "namespace": "tripgo-lab-02",
			"labels": map[string]any{
				"app.kubernetes.io/managed-by": "tripgoctl", "app.kubernetes.io/part-of": "tripgo-local",
				"tripgo.course/lab": "02", "tripgo.course/environment": "tripgo-lab-02",
			},
			"annotations": map[string]any{"tripgo.course/cluster-id": "cluster-id"},
		},
		"spec": map[string]any{
			"type":     "ClusterIP",
			"selector": map[string]any{"app.kubernetes.io/name": "jaeger", "app.kubernetes.io/instance": "tripgo-lab-02-jaeger"},
			"ports":    []any{map[string]any{"name": "otlp-grpc", "port": int64(4317), "targetPort": "otlp-grpc"}},
		},
	}}
	if err := verifyJaegerOTLPService(service, 2, "tripgo-lab-02", "cluster-id"); err != nil {
		t.Fatal(err)
	}
	service.Object["spec"].(map[string]any)["ports"] = []any{map[string]any{"name": "otlp-grpc", "port": int64(4318), "targetPort": "otlp-grpc"}}
	if err := verifyJaegerOTLPService(service, 2, "tripgo-lab-02", "cluster-id"); !errors.Is(err, cluster.ErrConflict) {
		t.Fatalf("drift error = %v", err)
	}
}

func TestWorkloadReadyRejectsStaleGeneration(t *testing.T) {
	t.Parallel()
	deployment := &unstructured.Unstructured{Object: map[string]any{
		"metadata": map[string]any{"generation": int64(2)},
		"spec":     map[string]any{"replicas": int64(1)},
		"status":   map[string]any{"observedGeneration": int64(1), "updatedReplicas": int64(1), "readyReplicas": int64(1), "availableReplicas": int64(1)},
	}}
	if workloadReady(deployment, 1) {
		t.Fatal("stale deployment generation reported ready")
	}
	deployment.Object["status"].(map[string]any)["observedGeneration"] = int64(2)
	if !workloadReady(deployment, 1) {
		t.Fatal("observed deployment was not reported ready")
	}
}

func TestRemoveGeneratedRejectsSymlinkLockOwnership(t *testing.T) {
	t.Parallel()
	directory := t.TempDir()
	tripgoPath := filepath.Join(directory, ".tripgo")
	if err := os.Mkdir(tripgoPath, 0o700); err != nil {
		t.Fatal(err)
	}
	foreign := filepath.Join(tripgoPath, "keep.txt")
	if err := os.WriteFile(foreign, []byte("keep"), 0o600); err != nil {
		t.Fatal(err)
	}
	marker := filepath.Join(directory, "marker.lock")
	content := envMarker + "\nlab = 1\nnamespace = \"tripgo-lab-01\"\ncluster_id = \"cluster-id\"\n"
	if err := os.WriteFile(marker, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(marker, filepath.Join(tripgoPath, "environment.lock")); err != nil {
		t.Fatal(err)
	}
	if err := removeGenerated(tripgoPath, true, 1, "tripgo-lab-01", "cluster-id"); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(foreign); err != nil {
		t.Fatalf("foreign .tripgo content was removed: %v", err)
	}
}

func TestLabFromNamespaceIsExact(t *testing.T) {
	t.Parallel()
	if lab, ok := labFromNamespace("tripgo-lab-01"); !ok || lab != 1 {
		t.Fatalf("valid namespace = %d, %v", lab, ok)
	}
	for _, invalid := range []string{"tripgo-lab-1", "tripgo-lab-01-extra", "other-01"} {
		if _, ok := labFromNamespace(invalid); ok {
			t.Errorf("namespace %q accepted", invalid)
		}
	}
}
