// Package lab reconciles isolated TripGo lab environments.
package lab

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/util/wait"
	"k8s.io/apimachinery/pkg/util/yaml"
	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/kubernetes"

	"github.com/course-go-autumn-2026/tripgo-infra/internal/catalog"
	"github.com/course-go-autumn-2026/tripgo-infra/internal/cluster"
	configenv "github.com/course-go-autumn-2026/tripgo-infra/internal/environment"
	"github.com/course-go-autumn-2026/tripgo-infra/internal/generator"
	"github.com/course-go-autumn-2026/tripgo-infra/internal/progress"
	"github.com/course-go-autumn-2026/tripgo-infra/internal/pushimage"
	"github.com/course-go-autumn-2026/tripgo-infra/internal/redact"
	redpandaconfig "github.com/course-go-autumn-2026/tripgo-infra/internal/redpanda"
)

const (
	envMarker      = "# Generated by tripgoctl. Do not edit manually."
	fieldManager   = "tripgoctl"
	readinessLimit = 3 * time.Minute
)

var (
	namespaceResource   = schema.GroupVersionResource{Version: "v1", Resource: "namespaces"}
	configMapResource   = schema.GroupVersionResource{Version: "v1", Resource: "configmaps"}
	secretResource      = schema.GroupVersionResource{Version: "v1", Resource: "secrets"}
	pvcResource         = schema.GroupVersionResource{Version: "v1", Resource: "persistentvolumeclaims"}
	serviceResource     = schema.GroupVersionResource{Version: "v1", Resource: "services"}
	podResource         = schema.GroupVersionResource{Version: "v1", Resource: "pods"}
	deploymentResource  = schema.GroupVersionResource{Group: "apps", Version: "v1", Resource: "deployments"}
	statefulSetResource = schema.GroupVersionResource{Group: "apps", Version: "v1", Resource: "statefulsets"}
)

// Cluster provides verified access and stores the global environment projection.
type Cluster interface {
	BeginEnvironmentOperation(context.Context) (*cluster.EnvironmentLease, error)
}

// ComponentStatus is the workload status shown by the CLI.
type ComponentStatus struct {
	Name        string
	Desired     int64
	Ready       int64
	ImageDigest string
}

// RuntimeStatus is the current state of one managed lab environment.
type RuntimeStatus struct {
	Lab        int
	Namespace  string
	State      string
	Components []ComponentStatus
}

type pushImageProvider interface {
	Ensure(context.Context) (string, error)
}

type podLogReader func(context.Context, cluster.Access, string, string, string, bool, int64) (io.ReadCloser, error)

// Service reconciles lab resources through the Kubernetes API.
type Service struct {
	cluster     Cluster
	pushImage   pushImageProvider
	newClient   func(cluster.Access) (dynamic.Interface, error)
	readPodLogs podLogReader
}

// NewService constructs the environment lifecycle service.
func NewService(clusterService Cluster) *Service {
	return &Service{
		cluster:   clusterService,
		pushImage: pushimage.NewProvider(),
		newClient: func(access cluster.Access) (dynamic.Interface, error) {
			return dynamic.NewForConfig(access.Config)
		},
		readPodLogs: func(ctx context.Context, access cluster.Access, namespace, pod, container string, follow bool, tail int64) (io.ReadCloser, error) {
			client, err := kubernetes.NewForConfig(access.Config)
			if err != nil {
				return nil, fmt.Errorf("create Kubernetes log client: %w", err)
			}
			return client.CoreV1().Pods(namespace).GetLogs(pod, &corev1.PodLogOptions{Container: container, Follow: follow, TailLines: &tail}).Stream(ctx)
		},
	}
}

// ConfiguredLab validates the current environment contract and returns its lab.
func (s *Service) ConfiguredLab(cwd string) (int, error) {
	config, err := loadCurrentConfig(cwd)
	if err != nil {
		return 0, err
	}
	return config.Lab, nil
}

// Start validates local inputs, reconciles the selected lab, waits for readiness, and writes local outputs.
func (s *Service) Start(ctx context.Context, cwd, version string) (RuntimeStatus, error) {
	progress.Report(ctx, progress.Stage, "Validating environment configuration")
	config, err := loadCurrentConfig(cwd)
	if err != nil {
		return RuntimeStatus{}, err
	}
	if err := ensureEnvWritable(filepath.Join(cwd, ".env")); err != nil {
		return RuntimeStatus{}, err
	}
	progress.Report(ctx, progress.Stage, "Connecting to the local cluster")
	lease, access, client, err := s.client(ctx)
	if err != nil {
		return RuntimeStatus{}, err
	}
	defer lease.Close()
	entry, _ := catalog.EnvironmentForLab(config.Lab)
	if err := ensureTripgoWritable(filepath.Join(cwd, ".tripgo")); err != nil {
		return RuntimeStatus{}, err
	}
	if _, getErr := client.Resource(namespaceResource).Get(ctx, entry.Namespace, metav1.GetOptions{}); getErr == nil {
		if err := verifyNamespace(ctx, client, entry.Namespace, config.Lab, access.ClusterID); err != nil {
			return RuntimeStatus{}, err
		}
	} else if !apierrors.IsNotFound(getErr) {
		return RuntimeStatus{}, fmt.Errorf("inspect namespace %s before apply: %w", entry.Namespace, getErr)
	}
	options := generator.Options{TripgoctlVersion: version, ClusterID: access.ClusterID}
	if config.Lab >= 3 {
		if s.pushImage == nil {
			return RuntimeStatus{}, errors.New("push service image provider is required")
		}
		options.PushImageReference, err = s.pushImage.Ensure(ctx)
		if err != nil {
			return RuntimeStatus{}, fmt.Errorf("prepare local Push Service image: %w", err)
		}
	}
	progress.Report(ctx, progress.Stage, "Generating Kubernetes resources")
	bundle, err := generator.Generate(config, options)
	if err != nil {
		return RuntimeStatus{}, err
	}
	if err := verifyManifestBundleOwnership(ctx, client, bundle, config.Lab, entry.Namespace, access.ClusterID); err != nil {
		return RuntimeStatus{}, err
	}
	progress.Report(ctx, progress.Stage, "Applying Kubernetes resources")
	for _, file := range bundle.Files {
		progress.Report(ctx, progress.Activity, "Applying "+file.Name)
		if err := applyManifest(ctx, client, file.Content, config.Lab, entry.Namespace, access.ClusterID); err != nil {
			return RuntimeStatus{}, fmt.Errorf("apply %s: %w", file.Name, err)
		}
	}
	progress.Report(ctx, progress.Stage, "Waiting for workloads")
	if err := waitForWorkloads(ctx, client, entry.Namespace, workloads(config.Lab), 1); err != nil {
		return RuntimeStatus{}, fmt.Errorf("%w: environment workloads did not become ready: %w", cluster.ErrPrerequisite, err)
	}
	// Project the successful Kubernetes transition before best-effort local output
	// writes so cluster status cannot report a ready namespace as absent.
	if err := lease.SetEnvironmentState(entry.Namespace, true, true); err != nil {
		return RuntimeStatus{}, err
	}
	progress.Report(ctx, progress.Stage, "Writing local configuration")
	if err := generator.Write(filepath.Join(cwd, ".tripgo"), bundle); err != nil {
		return RuntimeStatus{}, err
	}
	if err := writeEnv(filepath.Join(cwd, ".env"), config, version); err != nil {
		return RuntimeStatus{}, err
	}
	return s.statusWith(ctx, client, config, access.ClusterID)
}

// Status inspects the current environment without mutation.
func (s *Service) Status(ctx context.Context, cwd string) (RuntimeStatus, error) {
	config, err := loadCurrentConfig(cwd)
	if err != nil {
		return RuntimeStatus{}, err
	}
	lease, access, client, err := s.client(ctx)
	if err != nil {
		return RuntimeStatus{}, err
	}
	defer lease.Close()
	return s.statusWith(ctx, client, config, access.ClusterID)
}

// Stop scales all managed workloads to zero while retaining the namespace and PVCs.
func (s *Service) Stop(ctx context.Context, cwd, version string) (RuntimeStatus, error) {
	config, err := loadCurrentConfig(cwd)
	if err != nil {
		return RuntimeStatus{}, err
	}
	lease, access, client, err := s.client(ctx)
	if err != nil {
		return RuntimeStatus{}, err
	}
	defer lease.Close()
	entry, _ := catalog.EnvironmentForLab(config.Lab)
	if err := verifyNamespace(ctx, client, entry.Namespace, config.Lab, access.ClusterID); err != nil {
		return RuntimeStatus{}, err
	}
	if err := verifyWorkloadOwnership(ctx, client, entry.Namespace, config.Lab, access.ClusterID); err != nil {
		return RuntimeStatus{}, err
	}
	if config.Lab >= 4 {
		if err := verifyRedpandaResources(ctx, client, config.Lab, entry.Namespace, access.ClusterID); err != nil {
			return RuntimeStatus{}, err
		}
	}
	replicas := int64(0)
	options := generator.Options{
		TripgoctlVersion: version,
		ClusterID:        access.ClusterID,
		WorkloadReplicas: &replicas,
	}
	if config.Lab >= 3 {
		pushDeployment, getErr := client.Resource(deploymentResource).Namespace(entry.Namespace).Get(ctx, "push-service", metav1.GetOptions{})
		if getErr != nil {
			return RuntimeStatus{}, fmt.Errorf("inspect Push Service before stop: %w", getErr)
		}
		if err := verifyResourceOwnership(pushDeployment, config.Lab, entry.Namespace, access.ClusterID); err != nil {
			return RuntimeStatus{}, err
		}
		options.PushImageReference = deploymentImageReference(pushDeployment)
		if !strings.HasPrefix(options.PushImageReference, catalog.LocalPushImageRepository+"@sha256:") {
			return RuntimeStatus{}, fmt.Errorf("%w: Push Service deployment does not use the managed local image digest", cluster.ErrConflict)
		}
	}
	bundle, err := generator.Generate(config, options)
	if err != nil {
		return RuntimeStatus{}, err
	}
	if err := verifyManifestBundleOwnership(ctx, client, bundle, config.Lab, entry.Namespace, access.ClusterID); err != nil {
		return RuntimeStatus{}, err
	}
	for _, file := range bundle.Files {
		if err := applyManifestWhere(ctx, client, file.Content, config.Lab, entry.Namespace, access.ClusterID, func(object *unstructured.Unstructured) bool {
			return object.GetKind() == "Deployment" || object.GetKind() == "StatefulSet"
		}); err != nil {
			return RuntimeStatus{}, fmt.Errorf("scale environment workloads to zero: %w", err)
		}
	}
	if err := waitForWorkloads(ctx, client, entry.Namespace, workloads(config.Lab), 0); err != nil {
		return RuntimeStatus{}, err
	}
	if err := lease.SetEnvironmentState(entry.Namespace, true, false); err != nil {
		return RuntimeStatus{}, err
	}
	return s.statusWith(ctx, client, config, access.ClusterID)
}

// Reset deletes an owned namespace and recognized local generated files.
func (s *Service) Reset(ctx context.Context, cwd string) error {
	config, err := loadCurrentConfig(cwd)
	if err != nil {
		return err
	}
	lease, access, client, err := s.client(ctx)
	if err != nil {
		return err
	}
	defer lease.Close()
	entry, _ := catalog.EnvironmentForLab(config.Lab)
	err = verifyNamespace(ctx, client, entry.Namespace, config.Lab, access.ClusterID)
	if err != nil && !errors.Is(err, cluster.ErrPrerequisite) {
		return err
	}
	if err == nil {
		if deleteErr := client.Resource(namespaceResource).Delete(ctx, entry.Namespace, metav1.DeleteOptions{}); deleteErr != nil && !apierrors.IsNotFound(deleteErr) {
			return fmt.Errorf("delete namespace %s: %w", entry.Namespace, deleteErr)
		}
		if waitErr := wait.PollUntilContextTimeout(ctx, 500*time.Millisecond, readinessLimit, true, func(ctx context.Context) (bool, error) {
			_, getErr := client.Resource(namespaceResource).Get(ctx, entry.Namespace, metav1.GetOptions{})
			return apierrors.IsNotFound(getErr), getErrIfUnexpected(getErr)
		}); waitErr != nil {
			return fmt.Errorf("wait for namespace %s deletion: %w", entry.Namespace, waitErr)
		}
	}
	// The namespace is authoritative for known/running status. Update its
	// projection before cleaning local generated files, whose removal may fail.
	if err := lease.SetEnvironmentState(entry.Namespace, false, false); err != nil {
		return err
	}
	if err := removeGenerated(filepath.Join(cwd, ".env"), false); err != nil {
		return err
	}
	return removeGenerated(filepath.Join(cwd, ".tripgo"), true)
}

// Logs streams recent logs from a supported component in the current lab namespace.
func (s *Service) Logs(ctx context.Context, cwd, component string, follow bool, tail int64, output io.Writer) error {
	containerByComponent := map[string]string{
		"push-service":              "push-service",
		"redpanda":                  "redpanda",
		"redpanda-console":          "redpanda-console",
		"redpanda-topic-reconciler": "topic-reconciler",
	}
	container, supported := containerByComponent[component]
	if !supported {
		return fmt.Errorf("%w: logs are not available for component %s", cluster.ErrPrerequisite, component)
	}
	if tail < 0 {
		return fmt.Errorf("tail must be non-negative")
	}
	if output == nil {
		return errors.New("log output is required")
	}
	config, err := loadCurrentConfig(cwd)
	if err != nil {
		return err
	}
	if component == "push-service" && config.Lab < 3 {
		return fmt.Errorf("%w: Push Service is not part of lab %d", cluster.ErrPrerequisite, config.Lab)
	}
	if component != "push-service" && config.Lab < 4 {
		return fmt.Errorf("%w: Redpanda is not part of lab %d", cluster.ErrPrerequisite, config.Lab)
	}
	lease, access, client, err := s.client(ctx)
	if err != nil {
		return err
	}
	defer lease.Close()
	entry, _ := catalog.EnvironmentForLab(config.Lab)
	if err := verifyNamespace(ctx, client, entry.Namespace, config.Lab, access.ClusterID); err != nil {
		return err
	}
	pods, err := client.Resource(podResource).Namespace(entry.Namespace).List(ctx, metav1.ListOptions{LabelSelector: "app.kubernetes.io/name=" + component + ",app.kubernetes.io/instance=" + entry.Namespace + "-" + component})
	if err != nil {
		return fmt.Errorf("list %s pods: %w", component, err)
	}
	sort.Slice(pods.Items, func(i, j int) bool { return pods.Items[i].GetName() < pods.Items[j].GetName() })
	var pod *unstructured.Unstructured
	for i := range pods.Items {
		candidate := &pods.Items[i]
		if candidate.GetDeletionTimestamp() == nil {
			pod = candidate
			break
		}
	}
	if pod == nil {
		return fmt.Errorf("%w: no running %s pod in %s", cluster.ErrPrerequisite, component, entry.Namespace)
	}
	if err := verifyResourceOwnership(pod, config.Lab, entry.Namespace, access.ClusterID); err != nil {
		return err
	}
	if s.readPodLogs == nil {
		return errors.New("kubernetes log reader is required")
	}
	// A followed read can be long-lived. Ownership is verified under the
	// operation lease, but the read must not block later lifecycle mutations.
	lease.Close()
	stream, err := s.readPodLogs(ctx, access, entry.Namespace, pod.GetName(), container, follow, tail)
	if err != nil {
		return fmt.Errorf("open %s logs: %w", component, err)
	}
	defer func() { _ = stream.Close() }()
	reader := bufio.NewReader(stream)
	for {
		line, readErr := reader.ReadString('\n')
		if line != "" {
			if _, err := io.WriteString(output, redact.Text(line)); err != nil {
				return fmt.Errorf("write redacted %s logs: %w", component, err)
			}
		}
		if errors.Is(readErr, io.EOF) {
			return nil
		}
		if readErr != nil {
			return fmt.Errorf("stream %s logs: %w", component, readErr)
		}
	}
}

// List returns all namespaces owned by this cluster identity.
func (s *Service) List(ctx context.Context) ([]RuntimeStatus, error) {
	lease, access, client, err := s.client(ctx)
	if err != nil {
		return nil, err
	}
	defer lease.Close()
	list, err := client.Resource(namespaceResource).List(ctx, metav1.ListOptions{LabelSelector: "app.kubernetes.io/managed-by=tripgoctl,app.kubernetes.io/part-of=tripgo-local"})
	if err != nil {
		return nil, fmt.Errorf("list environments: %w", err)
	}
	result := make([]RuntimeStatus, 0, len(list.Items))
	for i := range list.Items {
		namespace := &list.Items[i]
		if namespace.GetAnnotations()["tripgo.course/cluster-id"] != access.ClusterID {
			continue
		}
		lab, ok := labFromNamespace(namespace.GetName())
		if !ok {
			continue
		}
		config := configenv.Config{SchemaVersion: configenv.SchemaVersion, Lab: lab}
		config.Components, _ = catalog.Components(lab)
		status, statusErr := s.statusWith(ctx, client, config, access.ClusterID)
		if statusErr != nil {
			if errors.Is(statusErr, cluster.ErrPrerequisite) || errors.Is(statusErr, cluster.ErrConflict) {
				components := make([]ComponentStatus, 0, len(workloads(lab)))
				for _, workload := range workloads(lab) {
					components = append(components, ComponentStatus{Name: workload.name})
				}
				result = append(result, RuntimeStatus{Lab: lab, Namespace: namespace.GetName(), State: "degraded", Components: components})
				continue
			}
			return nil, statusErr
		}
		result = append(result, status)
	}
	sort.Slice(result, func(i, j int) bool { return result[i].Lab < result[j].Lab })
	return result, nil
}

func (s *Service) client(ctx context.Context) (*cluster.EnvironmentLease, cluster.Access, dynamic.Interface, error) {
	lease, err := s.cluster.BeginEnvironmentOperation(ctx)
	if err != nil {
		return nil, cluster.Access{}, nil, err
	}
	access := lease.Access()
	client, err := s.newClient(access)
	if err != nil {
		lease.Close()
		return nil, cluster.Access{}, nil, fmt.Errorf("create Kubernetes client: %w", err)
	}
	return lease, access, client, nil
}

func (s *Service) statusWith(ctx context.Context, client dynamic.Interface, config configenv.Config, clusterID string) (RuntimeStatus, error) {
	entry, ok := catalog.EnvironmentForLab(config.Lab)
	if !ok {
		return RuntimeStatus{}, fmt.Errorf("unsupported lab %d", config.Lab)
	}
	if err := verifyNamespace(ctx, client, entry.Namespace, config.Lab, clusterID); err != nil {
		return RuntimeStatus{}, err
	}
	for _, expected := range endpointServices(config.Lab) {
		service, err := client.Resource(serviceResource).Namespace(entry.Namespace).Get(ctx, expected.name, metav1.GetOptions{})
		if apierrors.IsNotFound(err) {
			return RuntimeStatus{}, fmt.Errorf("%w: %s service is absent in %s; run tripgoctl environment start", cluster.ErrPrerequisite, expected.name, entry.Namespace)
		}
		if err != nil {
			return RuntimeStatus{}, fmt.Errorf("inspect %s service: %w", expected.name, err)
		}
		if err := verifyEndpointService(service, config.Lab, entry.Namespace, clusterID, expected); err != nil {
			return RuntimeStatus{}, err
		}
	}
	if config.Lab >= 2 {
		for _, internal := range []struct {
			name   string
			verify func(*unstructured.Unstructured, int, string, string) error
		}{
			{name: "otel-collector-metrics", verify: verifyMetricsService},
			{name: "jaeger-otlp", verify: verifyJaegerOTLPService},
		} {
			service, err := client.Resource(serviceResource).Namespace(entry.Namespace).Get(ctx, internal.name, metav1.GetOptions{})
			if apierrors.IsNotFound(err) {
				return RuntimeStatus{}, fmt.Errorf("%w: %s service is absent in %s; run tripgoctl environment start", cluster.ErrPrerequisite, internal.name, entry.Namespace)
			}
			if err != nil {
				return RuntimeStatus{}, fmt.Errorf("inspect %s service: %w", internal.name, err)
			}
			if err := internal.verify(service, config.Lab, entry.Namespace, clusterID); err != nil {
				return RuntimeStatus{}, err
			}
		}
	}
	if config.Lab >= 4 {
		if err := verifyRedpandaResources(ctx, client, config.Lab, entry.Namespace, clusterID); err != nil {
			return RuntimeStatus{}, err
		}
	}

	components := make([]ComponentStatus, 0, len(workloads(config.Lab)))
	allStopped := true
	allReady := true
	for _, workload := range workloads(config.Lab) {
		object, err := client.Resource(workload.resource).Namespace(entry.Namespace).Get(ctx, workload.name, metav1.GetOptions{})
		if apierrors.IsNotFound(err) {
			return RuntimeStatus{}, fmt.Errorf("%w: %s is absent in %s; run tripgoctl environment start", cluster.ErrPrerequisite, workload.name, entry.Namespace)
		}
		if err != nil {
			return RuntimeStatus{}, fmt.Errorf("inspect %s: %w", workload.name, err)
		}
		if err := verifyResourceOwnership(object, config.Lab, entry.Namespace, clusterID); err != nil {
			return RuntimeStatus{}, err
		}
		desired, _, _ := unstructured.NestedInt64(object.Object, "spec", "replicas")
		ready, _, _ := unstructured.NestedInt64(object.Object, "status", "readyReplicas")
		reference := workloadImageReference(object)
		digest := workloadImageDigest(object)
		if digest == "" {
			return RuntimeStatus{}, fmt.Errorf("%w: %s workload does not use an immutable image digest", cluster.ErrConflict, workload.name)
		}
		if workload.name == "push-service" && !strings.HasPrefix(reference, catalog.LocalPushImageRepository+"@sha256:") {
			return RuntimeStatus{}, fmt.Errorf("%w: Push Service deployment is not pinned to the managed local repository", cluster.ErrConflict)
		}
		components = append(components, ComponentStatus{Name: workload.name, Desired: desired, Ready: ready, ImageDigest: digest})
		allStopped = allStopped && desired == 0 && workloadReady(object, 0)
		allReady = allReady && desired > 0 && workloadReady(object, desired)
	}
	state := "starting"
	if allStopped {
		state = "stopped"
	} else if allReady {
		state = "ready"
	}
	return RuntimeStatus{Lab: config.Lab, Namespace: entry.Namespace, State: state, Components: components}, nil
}

func loadCurrentConfig(cwd string) (configenv.Config, error) {
	if cwd == "" {
		return configenv.Config{}, errors.New("working directory is required")
	}
	config, err := configenv.ParseFile(filepath.Join(cwd, "environment.toml"))
	if err != nil {
		return configenv.Config{}, err
	}
	if config.Lab < 1 || config.Lab > 5 {
		return configenv.Config{}, fmt.Errorf("%w: lab %d lifecycle is not available; this tripgoctl version supports labs 1 through 5", cluster.ErrPrerequisite, config.Lab)
	}
	return config, nil
}

func verifyManifestBundleOwnership(ctx context.Context, client dynamic.Interface, bundle generator.Bundle, lab int, namespace, clusterID string) error {
	for _, file := range bundle.Files {
		decoder := yaml.NewYAMLOrJSONDecoder(bytes.NewReader(file.Content), 4096)
		for {
			var raw json.RawMessage
			if err := decoder.Decode(&raw); err != nil {
				if errors.Is(err, io.EOF) {
					break
				}
				return fmt.Errorf("decode %s during ownership preflight: %w", file.Name, err)
			}
			if len(bytes.TrimSpace(raw)) == 0 {
				continue
			}
			object := &unstructured.Unstructured{Object: map[string]any{}}
			if err := json.Unmarshal(raw, &object.Object); err != nil {
				return fmt.Errorf("decode resource in %s during ownership preflight: %w", file.Name, err)
			}
			resource, err := resourceFor(object.GetAPIVersion(), object.GetKind())
			if err != nil {
				return err
			}
			var target dynamic.ResourceInterface
			if object.GetNamespace() == "" {
				target = client.Resource(resource)
			} else {
				target = client.Resource(resource).Namespace(object.GetNamespace())
			}
			existing, err := target.Get(ctx, object.GetName(), metav1.GetOptions{})
			if apierrors.IsNotFound(err) {
				continue
			}
			if err != nil {
				return fmt.Errorf("inspect existing %s/%s during ownership preflight: %w", object.GetKind(), object.GetName(), err)
			}
			if err := verifyResourceOwnership(existing, lab, namespace, clusterID); err != nil {
				return err
			}
		}
	}
	return nil
}

func applyManifest(ctx context.Context, client dynamic.Interface, content []byte, lab int, namespace, clusterID string) error {
	return applyManifestWhere(ctx, client, content, lab, namespace, clusterID, func(*unstructured.Unstructured) bool { return true })
}

func applyManifestWhere(ctx context.Context, client dynamic.Interface, content []byte, lab int, namespace, clusterID string, include func(*unstructured.Unstructured) bool) error {
	decoder := yaml.NewYAMLOrJSONDecoder(bytes.NewReader(content), 4096)
	for {
		var raw json.RawMessage
		if err := decoder.Decode(&raw); err != nil {
			if errors.Is(err, io.EOF) {
				return nil
			}
			return fmt.Errorf("decode manifest: %w", err)
		}
		if len(bytes.TrimSpace(raw)) == 0 {
			continue
		}
		object := &unstructured.Unstructured{Object: map[string]any{}}
		if err := json.Unmarshal(raw, &object.Object); err != nil {
			return fmt.Errorf("decode resource: %w", err)
		}
		if !include(object) {
			continue
		}
		resource, err := resourceFor(object.GetAPIVersion(), object.GetKind())
		if err != nil {
			return err
		}
		payload, err := json.Marshal(object.Object)
		if err != nil {
			return err
		}
		var target dynamic.ResourceInterface
		if object.GetNamespace() == "" {
			target = client.Resource(resource)
		} else {
			target = client.Resource(resource).Namespace(object.GetNamespace())
		}
		existing, getErr := target.Get(ctx, object.GetName(), metav1.GetOptions{})
		if getErr == nil {
			if err := verifyResourceOwnership(existing, lab, namespace, clusterID); err != nil {
				return err
			}
		} else if !apierrors.IsNotFound(getErr) {
			return fmt.Errorf("inspect existing %s/%s: %w", object.GetKind(), object.GetName(), getErr)
		}
		_, err = target.Patch(ctx, object.GetName(), types.ApplyPatchType, payload, metav1.PatchOptions{FieldManager: fieldManager})
		if err != nil {
			if apierrors.IsConflict(err) {
				return fmt.Errorf("%w: server-side apply conflict for %s/%s: %v", cluster.ErrConflict, object.GetKind(), object.GetName(), err)
			}
			return fmt.Errorf("server-side apply %s/%s: %w", object.GetKind(), object.GetName(), err)
		}
	}
}

func resourceFor(apiVersion, kind string) (schema.GroupVersionResource, error) {
	switch apiVersion + "/" + kind {
	case "v1/Namespace":
		return namespaceResource, nil
	case "v1/ConfigMap":
		return configMapResource, nil
	case "v1/Secret":
		return secretResource, nil
	case "v1/PersistentVolumeClaim":
		return pvcResource, nil
	case "v1/Service":
		return serviceResource, nil
	case "apps/v1/Deployment":
		return deploymentResource, nil
	case "apps/v1/StatefulSet":
		return statefulSetResource, nil
	default:
		return schema.GroupVersionResource{}, fmt.Errorf("unsupported Kubernetes resource %s %s", apiVersion, kind)
	}
}

func verifyNamespace(ctx context.Context, client dynamic.Interface, namespace string, lab int, clusterID string) error {
	object, err := client.Resource(namespaceResource).Get(ctx, namespace, metav1.GetOptions{})
	if apierrors.IsNotFound(err) {
		return fmt.Errorf("%w: environment %s does not exist; run tripgoctl environment start", cluster.ErrPrerequisite, namespace)
	}
	if err != nil {
		return fmt.Errorf("inspect namespace %s: %w", namespace, err)
	}
	if err := verifyResourceOwnership(object, lab, namespace, clusterID); err != nil {
		return fmt.Errorf("%w: namespace %s is not owned by this tripgoctl cluster", cluster.ErrConflict, namespace)
	}
	return nil
}

func verifyResourceOwnership(object *unstructured.Unstructured, lab int, namespace, clusterID string) error {
	labels := object.GetLabels()
	if labels["app.kubernetes.io/managed-by"] != "tripgoctl" ||
		labels["app.kubernetes.io/part-of"] != "tripgo-local" ||
		labels["tripgo.course/lab"] != fmt.Sprintf("%02d", lab) ||
		labels["tripgo.course/environment"] != namespace ||
		object.GetAnnotations()["tripgo.course/cluster-id"] != clusterID {
		return fmt.Errorf("%w: %s %s does not have matching tripgoctl ownership", cluster.ErrConflict, object.GetKind(), object.GetName())
	}
	return nil
}

func waitForWorkloads(ctx context.Context, client dynamic.Interface, namespace string, items []workload, expected int64) error {
	last := make(map[string]string, len(items))
	lastSummary := ""
	err := wait.PollUntilContextTimeout(ctx, time.Second, readinessLimit, true, func(ctx context.Context) (bool, error) {
		ready := true
		statuses := make([]string, 0, len(items))
		for _, item := range items {
			object, getErr := client.Resource(item.resource).Namespace(namespace).Get(ctx, item.name, metav1.GetOptions{})
			if getErr != nil {
				last[item.name] = "API read failed: " + getErr.Error()
				statuses = append(statuses, item.name+" unavailable")
				ready = false
				continue
			}
			desired, _, _ := unstructured.NestedInt64(object.Object, "spec", "replicas")
			readyReplicas, _, _ := unstructured.NestedInt64(object.Object, "status", "readyReplicas")
			statuses = append(statuses, fmt.Sprintf("%s %d/%d", item.name, readyReplicas, desired))
			if !workloadReady(object, expected) {
				observed, _, _ := unstructured.NestedInt64(object.Object, "status", "observedGeneration")
				last[item.name] = fmt.Sprintf("desired=%d ready=%d generation=%d observed=%d", desired, readyReplicas, object.GetGeneration(), observed)
				ready = false
				continue
			}
			delete(last, item.name)
		}
		summary := strings.Join(statuses, ", ")
		if summary != lastSummary {
			progress.Report(ctx, progress.Readiness, summary)
			lastSummary = summary
		}
		return ready, nil
	})
	if err == nil {
		return nil
	}
	names := make([]string, 0, len(last))
	for name := range last {
		names = append(names, name)
	}
	sort.Strings(names)
	details := make([]string, 0, len(names))
	for _, name := range names {
		details = append(details, name+" ("+last[name]+")")
	}
	if len(details) == 0 {
		return err
	}
	return fmt.Errorf("%w; not ready: %s", err, strings.Join(details, "; "))
}

type endpointPort struct {
	name        string
	catalogName string
	servicePort int64
	targetPort  string
}

type endpointService struct {
	name         string
	selectorName string
	ports        []endpointPort
}

type workload struct {
	name     string
	resource schema.GroupVersionResource
}

func workloads(lab int) []workload {
	items := []workload{{name: "postgres", resource: deploymentResource}}
	if lab >= 2 {
		for _, name := range []string{"otel-collector", "jaeger", "prometheus", "grafana"} {
			items = append(items, workload{name: name, resource: deploymentResource})
		}
	}
	if lab >= 3 {
		items = append(items, workload{name: "push-service", resource: deploymentResource})
	}
	if lab >= 4 {
		items = append(items,
			workload{name: "redpanda", resource: statefulSetResource},
			workload{name: "redpanda-console", resource: deploymentResource},
			workload{name: "redpanda-topic-reconciler", resource: deploymentResource},
		)
	}
	return items
}

func endpointServices(lab int) []endpointService {
	services := []endpointService{{name: "postgres", ports: []endpointPort{{name: "postgres", catalogName: "postgres", servicePort: 5432, targetPort: "postgres"}}}}
	if lab >= 2 {
		services = append(services,
			endpointService{name: "otel-collector", ports: []endpointPort{
				{name: "otlp-grpc", catalogName: "otel-grpc", servicePort: 4317, targetPort: "otlp-grpc"},
				{name: "otlp-http", catalogName: "otel-http", servicePort: 4318, targetPort: "otlp-http"},
			}},
			endpointService{name: "jaeger", ports: []endpointPort{{name: "ui", catalogName: "jaeger", servicePort: 16686, targetPort: "ui"}}},
			endpointService{name: "prometheus", ports: []endpointPort{{name: "http", catalogName: "prometheus", servicePort: 9090, targetPort: "http"}}},
			endpointService{name: "grafana", ports: []endpointPort{{name: "http", catalogName: "grafana", servicePort: 3000, targetPort: "http"}}},
		)
	}
	if lab >= 3 {
		services = append(services, endpointService{name: "push-service", ports: []endpointPort{
			{name: "http", catalogName: "push-http", servicePort: 8090, targetPort: "http"},
			{name: "grpc", catalogName: "push-grpc", servicePort: 9095, targetPort: "grpc"},
		}})
	}
	if lab >= 4 {
		services = append(services,
			endpointService{name: "redpanda-external", selectorName: "redpanda", ports: []endpointPort{{name: "kafka-external", catalogName: "redpanda-kafka", servicePort: 19092, targetPort: "kafka-external"}}},
			endpointService{name: "redpanda-console", ports: []endpointPort{{name: "http", catalogName: "redpanda-console", servicePort: 8080, targetPort: "http"}}},
		)
	}
	return services
}

func verifyEndpointService(service *unstructured.Unstructured, lab int, namespace, clusterID string, expected endpointService) error {
	if err := verifyResourceOwnership(service, lab, namespace, clusterID); err != nil {
		return err
	}
	serviceType, _, _ := unstructured.NestedString(service.Object, "spec", "type")
	selector, _, _ := unstructured.NestedStringMap(service.Object, "spec", "selector")
	ports, _, _ := unstructured.NestedSlice(service.Object, "spec", "ports")
	selectorName := expected.selectorName
	if selectorName == "" {
		selectorName = expected.name
	}
	if serviceType != "NodePort" || selector["app.kubernetes.io/name"] != selectorName || selector["app.kubernetes.io/instance"] != namespace+"-"+selectorName || len(ports) != len(expected.ports) {
		return fmt.Errorf("%w: %s service does not match the catalog endpoint", cluster.ErrConflict, expected.name)
	}
	for _, wanted := range expected.ports {
		catalogPort, _ := catalog.PortByName(lab, wanted.catalogName)
		found := false
		for _, item := range ports {
			port, ok := item.(map[string]any)
			if !ok {
				continue
			}
			name, _, _ := unstructured.NestedString(port, "name")
			servicePort, _, _ := unstructured.NestedInt64(port, "port")
			nodePort, _, _ := unstructured.NestedInt64(port, "nodePort")
			targetPort, _, _ := unstructured.NestedString(port, "targetPort")
			if name == wanted.name && servicePort == wanted.servicePort && nodePort == int64(catalogPort.NodePort) && targetPort == wanted.targetPort {
				found = true
				break
			}
		}
		if !found {
			return fmt.Errorf("%w: %s service port %s does not match the catalog endpoint", cluster.ErrConflict, expected.name, wanted.name)
		}
	}
	return nil
}

func verifyWorkloadOwnership(ctx context.Context, client dynamic.Interface, namespace string, lab int, clusterID string) error {
	for _, item := range workloads(lab) {
		object, err := client.Resource(item.resource).Namespace(namespace).Get(ctx, item.name, metav1.GetOptions{})
		if apierrors.IsNotFound(err) {
			return fmt.Errorf("%w: %s is absent in %s; run tripgoctl environment start", cluster.ErrPrerequisite, item.name, namespace)
		}
		if err != nil {
			return fmt.Errorf("inspect %s before lifecycle change: %w", item.name, err)
		}
		if err := verifyResourceOwnership(object, lab, namespace, clusterID); err != nil {
			return err
		}
	}
	return nil
}

func verifyRedpandaResources(ctx context.Context, client dynamic.Interface, lab int, namespace, clusterID string) error {
	topicsConfig, err := client.Resource(configMapResource).Namespace(namespace).Get(ctx, "redpanda-topics", metav1.GetOptions{})
	if apierrors.IsNotFound(err) {
		return fmt.Errorf("%w: redpanda-topics is absent in %s; run tripgoctl environment start", cluster.ErrPrerequisite, namespace)
	}
	if err != nil {
		return fmt.Errorf("inspect redpanda-topics: %w", err)
	}
	if err := verifyResourceOwnership(topicsConfig, lab, namespace, clusterID); err != nil {
		return err
	}
	data, found, err := unstructured.NestedStringMap(topicsConfig.Object, "data")
	if err != nil || !found {
		return fmt.Errorf("%w: redpanda-topics ConfigMap data is invalid", cluster.ErrConflict)
	}
	expectedData := redpandaconfig.ConfigMapData()
	if len(data) != len(expectedData) || data["topics"] != expectedData["topics"] || data["reconcile.sh"] != expectedData["reconcile.sh"] {
		return fmt.Errorf("%w: redpanda-topics ConfigMap does not match the managed reconciliation contract", cluster.ErrConflict)
	}

	redpandaService, err := client.Resource(serviceResource).Namespace(namespace).Get(ctx, "redpanda", metav1.GetOptions{})
	if apierrors.IsNotFound(err) {
		return fmt.Errorf("%w: redpanda is absent in %s; run tripgoctl environment start", cluster.ErrPrerequisite, namespace)
	}
	if err != nil {
		return fmt.Errorf("inspect redpanda service: %w", err)
	}
	if err := verifyResourceOwnership(redpandaService, lab, namespace, clusterID); err != nil {
		return err
	}
	statefulSet, err := client.Resource(statefulSetResource).Namespace(namespace).Get(ctx, "redpanda", metav1.GetOptions{})
	if err != nil {
		return fmt.Errorf("inspect Redpanda advertised listener: %w", err)
	}
	containers, _, _ := unstructured.NestedSlice(statefulSet.Object, "spec", "template", "spec", "containers")
	args := []any(nil)
	if len(containers) > 0 {
		container, _ := containers[0].(map[string]any)
		args, _, _ = unstructured.NestedSlice(container, "args")
	}
	port, _ := catalog.PortByName(lab, "redpanda-kafka")
	advertised := "--advertise-kafka-addr=internal://redpanda:9092,external://localhost:" + fmt.Sprint(port.HostPort)
	advertisedFound := false
	for _, arg := range args {
		advertisedFound = advertisedFound || arg == advertised
	}
	if !advertisedFound {
		return fmt.Errorf("%w: Redpanda advertised Kafka listener does not match lab %d host port", cluster.ErrConflict, lab)
	}
	claims, err := client.Resource(pvcResource).Namespace(namespace).List(ctx, metav1.ListOptions{LabelSelector: "app.kubernetes.io/managed-by=tripgoctl,tripgo.course/environment=" + namespace})
	if err != nil {
		return fmt.Errorf("list Redpanda persistent claims: %w", err)
	}
	redpandaClaims := 0
	for i := range claims.Items {
		claim := &claims.Items[i]
		if strings.HasPrefix(claim.GetName(), "data-redpanda-") {
			redpandaClaims++
			if err := verifyResourceOwnership(claim, lab, namespace, clusterID); err != nil {
				return err
			}
		}
	}
	if redpandaClaims != 1 {
		return fmt.Errorf("%w: expected one owned Redpanda PVC, found %d", cluster.ErrConflict, redpandaClaims)
	}
	return nil
}

func verifyMetricsService(service *unstructured.Unstructured, lab int, namespace, clusterID string) error {
	if err := verifyResourceOwnership(service, lab, namespace, clusterID); err != nil {
		return err
	}
	serviceType, _, _ := unstructured.NestedString(service.Object, "spec", "type")
	selector, _, _ := unstructured.NestedStringMap(service.Object, "spec", "selector")
	ports, _, _ := unstructured.NestedSlice(service.Object, "spec", "ports")
	validPort := false
	for _, item := range ports {
		port, ok := item.(map[string]any)
		if !ok {
			continue
		}
		name, _, _ := unstructured.NestedString(port, "name")
		servicePort, _, _ := unstructured.NestedInt64(port, "port")
		targetPort, _, _ := unstructured.NestedString(port, "targetPort")
		if name == "prometheus" && servicePort == 8889 && targetPort == "prometheus" {
			validPort = true
			break
		}
	}
	if serviceType != "ClusterIP" || selector["app.kubernetes.io/name"] != "otel-collector" || selector["app.kubernetes.io/instance"] != namespace+"-otel-collector" || len(ports) != 1 || !validPort {
		return fmt.Errorf("%w: otel-collector-metrics service does not match the internal metrics endpoint", cluster.ErrConflict)
	}
	return nil
}

func verifyJaegerOTLPService(service *unstructured.Unstructured, lab int, namespace, clusterID string) error {
	if err := verifyResourceOwnership(service, lab, namespace, clusterID); err != nil {
		return err
	}
	serviceType, _, _ := unstructured.NestedString(service.Object, "spec", "type")
	selector, _, _ := unstructured.NestedStringMap(service.Object, "spec", "selector")
	ports, _, _ := unstructured.NestedSlice(service.Object, "spec", "ports")
	validPort := false
	for _, item := range ports {
		port, ok := item.(map[string]any)
		if !ok {
			continue
		}
		name, _, _ := unstructured.NestedString(port, "name")
		servicePort, _, _ := unstructured.NestedInt64(port, "port")
		targetPort, _, _ := unstructured.NestedString(port, "targetPort")
		if name == "otlp-grpc" && servicePort == 4317 && targetPort == "otlp-grpc" {
			validPort = true
			break
		}
	}
	if serviceType != "ClusterIP" || selector["app.kubernetes.io/name"] != "jaeger" || selector["app.kubernetes.io/instance"] != namespace+"-jaeger" || len(ports) != 1 || !validPort {
		return fmt.Errorf("%w: jaeger-otlp service does not match the internal trace endpoint", cluster.ErrConflict)
	}
	return nil
}

func workloadImageReference(deployment *unstructured.Unstructured) string {
	containers, _, _ := unstructured.NestedSlice(deployment.Object, "spec", "template", "spec", "containers")
	if len(containers) == 0 {
		return ""
	}
	container, ok := containers[0].(map[string]any)
	if !ok {
		return ""
	}
	image, _, _ := unstructured.NestedString(container, "image")
	return image
}

func workloadImageDigest(deployment *unstructured.Unstructured) string {
	_, digest, found := strings.Cut(workloadImageReference(deployment), "@")
	if !found {
		return ""
	}
	return digest
}

func workloadReady(deployment *unstructured.Unstructured, expected int64) bool {
	desired, _, _ := unstructured.NestedInt64(deployment.Object, "spec", "replicas")
	observed, _, _ := unstructured.NestedInt64(deployment.Object, "status", "observedGeneration")
	updated, _, _ := unstructured.NestedInt64(deployment.Object, "status", "updatedReplicas")
	ready, _, _ := unstructured.NestedInt64(deployment.Object, "status", "readyReplicas")
	available, _, _ := unstructured.NestedInt64(deployment.Object, "status", "availableReplicas")
	return desired == expected && observed >= deployment.GetGeneration() && updated == expected && ready == expected && available == expected
}

func deploymentImageReference(deployment *unstructured.Unstructured) string {
	return workloadImageReference(deployment)
}

func ensureEnvWritable(path string) error {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("inspect .env: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
		return fmt.Errorf("%w: existing .env is not a regular generated file; move it aside and retry", cluster.ErrConflict)
	}
	file, err := os.Open(path) // #nosec G304 -- explicit project-local path.
	if err != nil {
		return fmt.Errorf("inspect .env: %w", err)
	}
	defer func() { _ = file.Close() }()
	line, readErr := bufio.NewReader(file).ReadString('\n')
	if readErr != nil && !errors.Is(readErr, io.EOF) {
		return fmt.Errorf("inspect .env marker: %w", readErr)
	}
	if strings.TrimSuffix(line, "\n") != envMarker {
		return fmt.Errorf("%w: existing .env is not generated by tripgoctl; move it aside and run tripgoctl environment start again", cluster.ErrConflict)
	}
	return nil
}

func ensureTripgoWritable(path string) error {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("inspect .tripgo: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
		return fmt.Errorf("%w: existing .tripgo is not a directory; move it aside and retry", cluster.ErrConflict)
	}
	rendered := filepath.Join(path, "rendered")
	renderedInfo, err := os.Lstat(rendered)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("inspect .tripgo/rendered: %w", err)
	}
	if renderedInfo.Mode()&os.ModeSymlink != 0 || !renderedInfo.IsDir() {
		return fmt.Errorf("%w: existing .tripgo/rendered is not a directory; move it aside and retry", cluster.ErrConflict)
	}
	return nil
}

func writeEnv(path string, config configenv.Config, version string) error {
	if err := ensureEnvWritable(path); err != nil {
		return err
	}
	var content strings.Builder
	fmt.Fprintln(&content, envMarker)
	fmt.Fprintln(&content, "# Source: environment.toml")
	fmt.Fprintf(&content, "# Lab: %d\n", config.Lab)
	fmt.Fprintf(&content, "# Generator: tripgoctl %s\n", version)
	for _, variable := range config.EnvironmentVariables() {
		fmt.Fprintf(&content, "%s=%s\n", variable.Name, variable.Value)
	}
	return atomicWrite(path, []byte(content.String()), 0o600)
}

func atomicWrite(path string, content []byte, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".tripgo-env-*")
	if err != nil {
		return fmt.Errorf("create temporary .env: %w", err)
	}
	temporaryPath := temporary.Name()
	defer func() { _ = os.Remove(temporaryPath) }()
	defer func() { _ = temporary.Close() }()
	if err := temporary.Chmod(mode); err != nil {
		return err
	}
	if _, err := temporary.Write(content); err != nil {
		return err
	}
	if err := temporary.Sync(); err != nil {
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		return fmt.Errorf("install .env: %w", err)
	}
	directory, err := os.Open(filepath.Dir(path)) // #nosec G304 -- explicit project-local directory.
	if err != nil {
		return fmt.Errorf("open .env directory for sync: %w", err)
	}
	defer func() { _ = directory.Close() }()
	if err := directory.Sync(); err != nil {
		return fmt.Errorf("sync .env directory: %w", err)
	}
	return nil
}

func removeGenerated(path string, directory bool) error {
	if directory {
		info, err := os.Lstat(path)
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		if err != nil {
			return fmt.Errorf("inspect generated directory: %w", err)
		}
		if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
			return nil
		}
		rendered := filepath.Join(path, "rendered")
		renderedInfo, renderedErr := os.Lstat(rendered)
		if renderedErr == nil && renderedInfo.Mode()&os.ModeSymlink == 0 && renderedInfo.IsDir() {
			if err := os.RemoveAll(rendered); err != nil {
				return err
			}
		} else if renderedErr != nil && !errors.Is(renderedErr, os.ErrNotExist) {
			return fmt.Errorf("inspect generated rendered directory: %w", renderedErr)
		}
		entries, err := os.ReadDir(path)
		if err != nil {
			return fmt.Errorf("inspect generated directory contents: %w", err)
		}
		if len(entries) == 0 {
			return os.Remove(path)
		}
		return nil
	}
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("inspect generated .env: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
		return nil
	}
	file, err := os.Open(path) // #nosec G304 -- explicit project-local path.
	if err != nil {
		return fmt.Errorf("inspect generated .env: %w", err)
	}
	line, readErr := bufio.NewReader(file).ReadString('\n')
	closeErr := file.Close()
	if readErr != nil && !errors.Is(readErr, io.EOF) {
		return fmt.Errorf("inspect generated .env marker: %w", readErr)
	}
	if closeErr != nil {
		return fmt.Errorf("close generated .env: %w", closeErr)
	}
	if strings.TrimSuffix(line, "\n") != envMarker {
		return nil
	}
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return nil
}

func getErrIfUnexpected(err error) error {
	if err == nil || apierrors.IsNotFound(err) {
		return nil
	}
	return err
}

func labFromNamespace(namespace string) (int, bool) {
	var lab int
	if _, err := fmt.Sscanf(namespace, "tripgo-lab-%02d", &lab); err != nil || lab < 1 || lab > 5 {
		return 0, false
	}
	expected, _ := catalog.Namespace(lab)
	return lab, expected == namespace
}
